FROM node:20-alpine as install-stage

WORKDIR /app
COPY . .

RUN npm ci

FROM node:20-alpine as build-stage
COPY --from=install-stage /app /app
WORKDIR /app

RUN npm run lint && \
    npm run build && \
    npm run test

FROM node:20-alpine as run-stage
COPY --from=build-stage /app /app
WORKDIR /app

EXPOSE 8081
EXPOSE 8082
EXPOSE 8083
EXPOSE 8084

CMD ["npm", "start"]


