services:
  auth:
    build: ./apps/auth
    ports:
      - "8084:80"

  lisa:
    build: ./apps/lisa
    ports:
      - "8081:80"

  max:
    build: ./apps/max
    ports:
      - "8082:80"

  tom:
    build: ./apps/tom
    ports:
      - "8083:80"
